site_name: LeetSolve
theme:
  name: readthedocs
  highlightjs: true
copyright: Copyright (c) 2023, Nhut Nguyen
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
