[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "leetsolve"
authors = [{name = "Nhut Nguyen", email = "nhut@nhutnguyen.com"}]
dynamic = ["version", "description"]
